// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application";

import AlertController from "./alert_controller";
application.register("alert", AlertController);

import CopyController from "./copy_controller";
application.register("copy", CopyController);
